name: ChatGPT CI

on: pull_request

jobs:
  test:
    name: ChatGPT explain code
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT explain code
        uses: cirolini/chatgpt-github-actions@v1.3
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY  }}
          github_token: ${{ secrets.GH_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_engine: "gpt-3.5-turbo"
          openai_temperature: 1
          openai_max_tokens: 2048
          mode: file
