name: ChatGPT CI

on: pull_request

jobs:
  test:
    name: ChatGPT explain code
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT explain code
        uses: magnificode-ltd/chatgpt-code-reviewer@v0.0.8
        with:
          model: gpt-4
          max_tokens: 4096
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
