name: ChatGPT CI

on: pull_request

jobs:
  test:
    name: ChatGPT explain code
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT explain code
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: English
          MODEL: 'gpt-3.5-turbo'
          top_p: 1
          temperature: 1
